### ISSUE TITLE
Unknown references to BezierKit.min(...) and BezierKit.max(...)

### ISSUE THREAD

**Issue by gregcotten** [hfutrell/BezierKit#5] opened 2017-08-19 00:20 UTC
Not sure why but this namespacing doesn't work if you just pull in the Library folder into a project!

Your library is great - thanks so much for making it!

**Comment by hfutrell** [comment] 2017-12-31 01:45
@gregcotten my apologies for taking so long to respond to this issue: Github did not notify me that the issue had been opened.

I believe that the issue is that if you pull the Library directory into another project then XCode does not recognize it as a separate Swift module. I've been working on the library with CocoaPods in mind, but I'll see if there is some way to namespace the code so that it'll work if you use it as you have.

**Comment by hfutrell** [comment] 2017-12-31 01:59
From the Swift 4 documentation:

```Each build target (such as an app bundle or framework) in Xcode is treated as a separate module in Swift. If you group together aspects of your app’s code as a stand-alone framework—perhaps to encapsulate and reuse that code across multiple applications—then everything you define within that framework will be part of a separate module when it’s imported and used within an app, or when it’s used within another framework.```

To me this says that it's unfortunately to get BezierKit to be recognized as a separate module unless its in a separate target. That will happen if you use BezierKit with Cocoapods, but not if you drop it into an existing project as you have.

What I'm going to do for now is make it so that the min function belongs to Point as a static function. Then calling `BKPoint.min` should work. I've pushed a fix to the 0.0.5 branch.

**Comment by hfutrell** [comment] 2017-12-31 02:06
@gregcotten I've pushed a fix to the `0.0.4` branch. Thanks for bringing it to my attention @gregcotten !

**Closed by hfutrell** 2017-12-31 02:06 UTC
Labels: enhancement
